Vagrant::Config.run do |config|
  config.vm.box = "millisami-10-04-server-amd64"
  config.vm.customize do |vm|
    vm.name = "QtPy-Webkit2png"
    vm.memory_size = 256
  end
  config.vm.boot_mode = :gui

  # Assign this VM to a host only network IP, allowing you to access it
  # via the IP.
  config.vm.network "33.33.33.100"

end
